function safeQuery(selector){try{return document.querySelector(selector)}catch{return null}}
function safeQueryAll(selector){try{return Array.from(document.querySelectorAll(selector))}catch{return []}}
function initLoader(){const loader=safeQuery('.loader');if(!loader)return;window.addEventListener('load',()=>{loader.classList.add('hide');setTimeout(()=>{if(loader.parentNode)loader.parentNode.removeChild(loader)},350)})}
function initTyping(){const el=safeQuery('.typing');if(!el)return;const phrases=['Aspiring Data Analyst','AI & ML Enthusiast','Final Year B.Tech CSE (Data Science)','Business Intelligence Learner'];let phraseIndex=0;let charIndex=0;let deleting=false;const speed=75;const pause=1600;function update(){const text=phrases[phraseIndex];if(!deleting){el.textContent=text.slice(0,charIndex+1);charIndex++;if(charIndex===text.length){deleting=true;setTimeout(update,pause);return}} else {el.textContent=text.slice(0,charIndex-1);charIndex--;if(charIndex===0){deleting=false;phraseIndex=(phraseIndex+1)%phrases.length}}setTimeout(update,deleting?35:speed)}update()}
function revealOnScroll(){safeQueryAll('.reveal').forEach(el=>{const rect=el.getBoundingClientRect();if(rect.top < (window.innerHeight||document.documentElement.clientHeight)-80){el.classList.add('active')}})}
function initLightbox(){const modal=safeQuery('.modal');if(!modal)return;const imgEl=safeQuery('.modal img');if(!imgEl)return;safeQueryAll('.lightbox').forEach(img=>{img.addEventListener('click',()=>{const src=img.dataset.src||img.src;if(src){imgEl.src=src;modal.classList.add('show');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}})});modal.addEventListener('click',e=>{if(e.target===modal){modal.classList.remove('show');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}})}
function animateProgress(){safeQueryAll('.progress > i').forEach(el=>{const pct=Number(el.dataset.progress||el.getAttribute('data-progress')||0);if(!Number.isFinite(pct))return;setTimeout(()=>{el.style.width=Math.min(100,Math.max(0,pct))+'%'},220)})}
function initTopButton(){const topBtn=safeQuery('.top-btn');if(!topBtn)return;window.addEventListener('scroll',()=>{topBtn.classList.toggle('show',window.scrollY>300)});topBtn.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}))}
function initSmoothAnchors(){safeQueryAll('a[href^="#"]').forEach(link=>{link.addEventListener('click',event=>{const targetId=link.getAttribute('href');const target=safeQuery(targetId);if(target){event.preventDefault();target.scrollIntoView({behavior:'smooth'})}})})}
function initExternalLinks(){safeQueryAll('a[target="_blank"]').forEach(link=>{link.setAttribute('rel','noopener noreferrer')})}
function initPage(){initLoader();initTyping();revealOnScroll();initLightbox();animateProgress();initTopButton();initSmoothAnchors();initExternalLinks();}
document.addEventListener('DOMContentLoaded',initPage);window.addEventListener('scroll',revealOnScroll);
